name: "Setup llcppg"
description: "Install dependencies, set up Go, download LLGo release, install llcppg"
inputs:
  go:
    description: "Go version to install"
    default: "1.23"
  llgo:
    description: "LLGo version to download (e.g. v0.11.6)"
    default: "v0.11.6"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: ${{inputs.go}}
  - name: Install dependencies
    if: runner.os == 'macOS'
    shell: bash
    run: |
      brew install bdw-gc openssl libffi libuv
      brew install zlib # for llgo test .
      brew link --force zlib # for llgo test .
      brew link --force libffi
  - name: Install dependencies
    shell: bash
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y pkg-config libgc-dev libssl-dev zlib1g-dev libffi-dev libuv1-dev
  - name: Download LLGo release
    shell: bash
    run: |
      bash .github/actions/setup-llcppg/download-llgo.sh ${{inputs.llgo}} .llgo
      echo "$GITHUB_WORKSPACE/.llgo/bin" >> $GITHUB_PATH
      echo "$GITHUB_WORKSPACE/.llgo/crosscompile/clang/bin" >> $GITHUB_PATH
      export LLGO_ROOT=$GITHUB_WORKSPACE/.llgo
      echo "LLGO_ROOT=$LLGO_ROOT" >> $GITHUB_ENV
  - name: Verify LLGo installation
    shell: bash
    run: |
      echo "LLGO_ROOT: $LLGO_ROOT"
      llgo version
      llvm-nm --version
  - name: Build
    shell: bash
    run: go build -v ./...

  - name: Install llcppg modules
    shell: bash
    run: |
      echo "Using LLGO_ROOT: $LLGO_ROOT"
      llgo install ./_xtool/llclang
      bash ./install.sh
